/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Seba
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("IMG/rosaViento.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        PanelAgencia = new javax.swing.JPanel();
        btnAgentes = new javax.swing.JButton();
        btnEmpresasTransporte = new javax.swing.JButton();
        btnAseguradora = new javax.swing.JButton();
        PanelColegio = new javax.swing.JPanel();
        btnCursos = new javax.swing.JButton();
        btnColegios = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnApoderados = new javax.swing.JButton();
        PanelTours = new javax.swing.JPanel();
        btnTours = new javax.swing.JButton();
        btnSeguro = new javax.swing.JButton();
        btnEstadias = new javax.swing.JButton();
        btnActividadesGira = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A.V.O.T. Local");
        setUndecorated(true);

        PanelTitulo.setBackground(new java.awt.Color(30, 160, 250));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A.V.O.T.");

        btnSalir.setBackground(new java.awt.Color(0, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        PanelAgencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion Agencia"));

        btnAgentes.setBackground(new java.awt.Color(0, 204, 255));
        btnAgentes.setText("Agentes");
        btnAgentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentesActionPerformed(evt);
            }
        });

        btnEmpresasTransporte.setBackground(new java.awt.Color(0, 204, 255));
        btnEmpresasTransporte.setText("Empresa Transporte");
        btnEmpresasTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresasTransporteActionPerformed(evt);
            }
        });

        btnAseguradora.setText("Aseguradoras");
        btnAseguradora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAseguradoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAgenciaLayout = new javax.swing.GroupLayout(PanelAgencia);
        PanelAgencia.setLayout(PanelAgenciaLayout);
        PanelAgenciaLayout.setHorizontalGroup(
            PanelAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgenciaLayout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addGroup(PanelAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpresasTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgentes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        PanelAgenciaLayout.setVerticalGroup(
            PanelAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgenciaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAgentes)
                .addGap(57, 57, 57)
                .addComponent(btnEmpresasTransporte)
                .addGap(69, 69, 69)
                .addComponent(btnAseguradora)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        PanelColegio.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestionar Colegios"));

        btnCursos.setBackground(new java.awt.Color(0, 204, 255));
        btnCursos.setText("Cursos");
        btnCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosActionPerformed(evt);
            }
        });

        btnColegios.setBackground(new java.awt.Color(0, 204, 255));
        btnColegios.setText("Colegios");
        btnColegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColegiosActionPerformed(evt);
            }
        });

        btnAlumnos.setBackground(new java.awt.Color(0, 204, 255));
        btnAlumnos.setText("Alumnos");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        btnApoderados.setBackground(new java.awt.Color(0, 204, 255));
        btnApoderados.setText("Apoderados");
        btnApoderados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApoderadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelColegioLayout = new javax.swing.GroupLayout(PanelColegio);
        PanelColegio.setLayout(PanelColegioLayout);
        PanelColegioLayout.setHorizontalGroup(
            PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColegioLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApoderados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColegios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        PanelColegioLayout.setVerticalGroup(
            PanelColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColegioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnApoderados)
                .addGap(18, 18, 18)
                .addComponent(btnCursos)
                .addGap(18, 18, 18)
                .addComponent(btnAlumnos)
                .addGap(18, 18, 18)
                .addComponent(btnColegios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTours.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion Tours"));

        btnTours.setBackground(new java.awt.Color(0, 204, 255));
        btnTours.setText("Tours");
        btnTours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToursActionPerformed(evt);
            }
        });

        btnSeguro.setBackground(new java.awt.Color(0, 204, 255));
        btnSeguro.setText("Seguros");
        btnSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguroActionPerformed(evt);
            }
        });

        btnEstadias.setBackground(new java.awt.Color(0, 204, 255));
        btnEstadias.setText("Estadias");
        btnEstadias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadiasActionPerformed(evt);
            }
        });

        btnActividadesGira.setBackground(new java.awt.Color(0, 204, 255));
        btnActividadesGira.setText("Actividades Gira");
        btnActividadesGira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadesGiraActionPerformed(evt);
            }
        });

        btnViajes.setBackground(new java.awt.Color(0, 204, 255));
        btnViajes.setText("Viajes");
        btnViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelToursLayout = new javax.swing.GroupLayout(PanelTours);
        PanelTours.setLayout(PanelToursLayout);
        PanelToursLayout.setHorizontalGroup(
            PanelToursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelToursLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(PanelToursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnActividadesGira, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstadias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTours, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        PanelToursLayout.setVerticalGroup(
            PanelToursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelToursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTours)
                .addGap(18, 18, 18)
                .addComponent(btnEstadias)
                .addGap(18, 18, 18)
                .addComponent(btnSeguro)
                .addGap(18, 18, 18)
                .addComponent(btnActividadesGira)
                .addGap(18, 18, 18)
                .addComponent(btnViajes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelTours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelTours, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAgencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelColegio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApoderadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApoderadosActionPerformed
        this.setVisible(false);
        GestionApoderado x = new GestionApoderado();
        x.setVisible(true);
    }//GEN-LAST:event_btnApoderadosActionPerformed

    private void btnToursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToursActionPerformed
        this.setVisible(false);
        GestionTour x = new GestionTour();
        x.setVisible(true);
    }//GEN-LAST:event_btnToursActionPerformed

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        this.setVisible(false);
        GestionViaje x = new GestionViaje();
        x.setVisible(true);
    }//GEN-LAST:event_btnViajesActionPerformed

    private void btnSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguroActionPerformed
        this.setVisible(false);
        GestionSeguro x = new GestionSeguro();
        x.setVisible(true);
    }//GEN-LAST:event_btnSeguroActionPerformed

    private void btnEstadiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadiasActionPerformed
        this.setVisible(false);
        GestionEstadia x = new GestionEstadia();
        x.setVisible(true);
    }//GEN-LAST:event_btnEstadiasActionPerformed

    private void btnActividadesGiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadesGiraActionPerformed
        this.setVisible(false);
        GestionActividadGira x = new GestionActividadGira();
        x.setVisible(true);
    }//GEN-LAST:event_btnActividadesGiraActionPerformed

    private void btnCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosActionPerformed
        this.setVisible(false);
        GestionCurso x = new GestionCurso();
        x.setVisible(true);
    }//GEN-LAST:event_btnCursosActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        this.setVisible(false);
        GestionAlumno x = new GestionAlumno();
        x.setVisible(true);
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnColegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColegiosActionPerformed
        this.setVisible(false);
        GestionColegio x = new GestionColegio();
        x.setVisible(true);
    }//GEN-LAST:event_btnColegiosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentesActionPerformed
        this.setVisible(false);
        GestionAgente x = new GestionAgente();
        x.setVisible(true);
    }//GEN-LAST:event_btnAgentesActionPerformed

    private void btnEmpresasTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasTransporteActionPerformed
        this.setVisible(false);
        GestionEmpresaTransporte x = new GestionEmpresaTransporte();
        x.setVisible(true);
    }//GEN-LAST:event_btnEmpresasTransporteActionPerformed

    private void btnAseguradoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAseguradoraActionPerformed
        this.setVisible(false);
        GestionAseguradora x = new GestionAseguradora();
        x.setVisible(true);
    }//GEN-LAST:event_btnAseguradoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAgencia;
    private javax.swing.JPanel PanelColegio;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JPanel PanelTours;
    private javax.swing.JButton btnActividadesGira;
    private javax.swing.JButton btnAgentes;
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnApoderados;
    private javax.swing.JButton btnAseguradora;
    private javax.swing.JButton btnColegios;
    private javax.swing.JButton btnCursos;
    private javax.swing.JButton btnEmpresasTransporte;
    private javax.swing.JButton btnEstadias;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeguro;
    private javax.swing.JButton btnTours;
    private javax.swing.JButton btnViajes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
